DEBUG:root:::while parsing json: Expecting value: line 1 column 1 (char 0)
DEBUG:root:user_agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36
DEBUG:root:self.cookie = 'C=0; O=0; V=aaf001987659acf4574d5f5437231ea761c66b2c4b2b96.41167953; usprivacy=1YNY; OptanonConsent=isIABGlobal=false&datestamp=Fri+Dec+24+2021+16%3A52%3A02+GMT-0800+(Pacific+Standard+Time)&version=6.18.0&hosts=&consentId=badbec39-c4c2-44a0-9a82-34d432c8f6ce&interactionCount=1&landingPath=NotLandingPage&groups=snc%3A1%2Cfnc%3A1%2Cprf%3A1%2CSPD_BG%3A1%2Ctrg%3A1&AwaitingReconsent=false; _vid_t=l1NILaQN7Oi5mHRDjgTBIsa57DShcvnfc4nqsQ6Td5scfmuy5RXb/oNnL7sHJ/8g7yRr6+yU9vlyfw==; DFID=web|4mUuaolFC5nG0RLMFUip; chgmfatoken=%5B%20%22account_sharing_mfa%22%20%3D%3E%201%2C%20%22user_uuid%22%20%3D%3E%20d7d00710-8e0d-49ab-ac90-a68c3eedf759%2C%20%22created_date%22%20%3D%3E%202021-12-25T01%3A02%3A24.159Z%20%5D; U=930632b00f9f9e2ce96274d3ec7a8de8; intlPaQExitIntentModal=hide; forterToken=a6cd91d7875c479980a51302fcfd8f78_1640766556082_69_dUAL43-mnts-ants_13ck; id_token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImphY29iY2hhbWllQGdtYWlsLmNvbSIsImlzcyI6Imh1Yi5jaGVnZy5jb20iLCJzdWIiOiJkN2QwMDcxMC04ZTBkLTQ5YWItYWM5MC1hNjhjM2VlZGY3NTkiLCJhdWQiOiJDSEdHIiwiaWF0IjoxNjQwNzY2NTYzLCJleHAiOjE2NTYzMTg1NjMsInJlcGFja2VyX2lkIjoiYXB3In0.fYmGGaGUtgdsJZeeU2nwUxUQFgRcRYCmmgvOw4lduU836KmJefL9avwYiCimhnLo1bfV9AW4GIyv0-qkMKyhlMuoHQJIUmmVzl4jvfzJM8_6ovPPLhgGCC_qgs2ppstmtda3y1Mz1RDJd9ClHdbJwZjpljWfVpJBEa7CWwZRpmCw-HuMFZAmuQ4qFCIUaPBpcj8vJl02PjQBkNw4xspbcH81jDsWUnv86GuTIYs0xhb88ngL7F-fKRhuKFUOEH3dQhnmb6V0Fqw9Bkia6oQm8oS1OvTFlcaduk9SWhr5n5LHnse6ucnwzttnJ12RMMES4OAoiF9DLB0rBr1S_IP14A; chgcsdmtoken=%7B%22user_uuid%22%3A%22d7d00710-8e0d-49ab-ac90-a68c3eedf759%22%2C%22created_date%22%3A%222021-12-29T08%3A29%3A32.681Z%22%2C%22account_sharing_device_management%22%3A1%7D; PHPSESSID=e0863859c70dacf0cc4c063b09f39c8b; user_geo_location=%7B%22country_iso_code%22%3A%22US%22%2C%22country_name%22%3A%22United+States%22%2C%22region%22%3A%22CA%22%2C%22region_full%22%3A%22California%22%2C%22city_name%22%3A%22West+Hollywood%22%2C%22postal_code%22%3A%2290069%22%2C%22locale%22%3A%7B%22localeCode%22%3A%5B%22en-US%22%5D%7D%7D; SU=KTb4WfSFXHFScz_oSGvgO8kqvgRSLTPAoTm_VIxKD5HE_8l721Mb8jHOzS8OVGIMp-3IAy-o5l877k91B1WlmEbZz5cMwkMd1zZmyeGDM9P7i_AoINICNrnLc3R53z6w; CSessionID=947ef918-4e86-4287-9346-50faf14fa0d0; exp=A803B%7CA560B%7CC026A%7CA127B; expkey=B918818D57319208B9A8FB202AC886C8; chegg_web_cbr_id=a; opt-user-profile=aaf001987659acf4574d5f5437231ea761c66b2c4b2b96.41167953%252C20738153433%253A20767183433; CVID=f6fc8283-d16f-4f49-9cde-0284ddc417a3; CSID=1641285114834; local_fallback_mcid=90200135162327362100423005922821524951; s_ecid=MCMID|90200135162327362100423005922821524951; mcid=90200135162327362100423005922821524951'
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): www.chegg.com:443
ERROR:flaskAPI:Exception on /urlBox [GET]
Traceback (most recent call last):
  File "/Users/jacobchamie/opt/anaconda3/lib/python3.9/site-packages/urllib3/connectionpool.py", line 696, in urlopen
    self._prepare_proxy(conn)
  File "/Users/jacobchamie/opt/anaconda3/lib/python3.9/site-packages/urllib3/connectionpool.py", line 964, in _prepare_proxy
    conn.connect()
  File "/Users/jacobchamie/opt/anaconda3/lib/python3.9/site-packages/urllib3/connection.py", line 371, in connect
    self._tunnel()
  File "/Users/jacobchamie/opt/anaconda3/lib/python3.9/http/client.py", line 929, in _tunnel
    raise OSError(f"Tunnel connection failed: {code} {message.strip()}")
OSError: Tunnel connection failed: 407 Proxy Authentication Required

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jacobchamie/opt/anaconda3/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/Users/jacobchamie/opt/anaconda3/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/Users/jacobchamie/opt/anaconda3/lib/python3.9/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.chegg.com', port=443): Max retries exceeded with url: /homework-help/questions-and-answers/find-region-integration-2x-4y-1-da-bounded-y-x-2-y-x-3-evaluate-double-integrals-q5681991 (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 407 Proxy Authentication Required')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jacobchamie/opt/anaconda3/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/jacobchamie/opt/anaconda3/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/jacobchamie/opt/anaconda3/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/jacobchamie/opt/anaconda3/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/jacobchamie/opt/anaconda3/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/jacobchamie/opt/anaconda3/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/jacobchamie/Desktop/chegg-scraper-main/flaskAPI.py", line 29, in urlLink
    parseAnswer = Downloader.main(url)
  File "/Users/jacobchamie/Desktop/chegg-scraper-main/cheggscraper/Downloader.py", line 68, in main
    return Chegg.url_to_html(url, file_name_format=default_save_file_format)
  File "/Users/jacobchamie/Desktop/chegg-scraper-main/cheggscraper/CheggScraper.py", line 526, in url_to_html
    html_res_text = self._get_response_text(url=url)
  File "/Users/jacobchamie/Desktop/chegg-scraper-main/cheggscraper/CheggScraper.py", line 310, in _get_response_text
    response = self._web_response(url, headers, expected_status, note, error_note)
  File "/Users/jacobchamie/Desktop/chegg-scraper-main/cheggscraper/CheggScraper.py", line 290, in _web_response
    response = requests.get(
  File "/Users/jacobchamie/opt/anaconda3/lib/python3.9/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/Users/jacobchamie/opt/anaconda3/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/jacobchamie/opt/anaconda3/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/jacobchamie/opt/anaconda3/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/Users/jacobchamie/opt/anaconda3/lib/python3.9/site-packages/requests/adapters.py", line 510, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='www.chegg.com', port=443): Max retries exceeded with url: /homework-help/questions-and-answers/find-region-integration-2x-4y-1-da-bounded-y-x-2-y-x-3-evaluate-double-integrals-q5681991 (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 407 Proxy Authentication Required')))
